site_name: Waterlagen
repo_url: https://github.com/d2hydro/waterlagen
repo_name: d2hydro/waterlagen

theme:
  name: material
  language: nl
  logo: icons/logo/globe_only.png
  favicon: icons/logo/favicon.png
  highlightjs: true
  features:
    - navigation.tabs
    - content.code.copy
  palette: 
    primary: blue

nav:
  - Home: 
      - Algemeen: index.md
      - DataStore: datastore.md
      - Downloads: downloads.md
      - Bewerkingen: bewerkingen.md
  - Code Reference:
      - AHN: reference/ahn.md
      - BAG: reference/bag.md
      - BGT: reference/bgt.md
      - DataStore: reference/datastore.md
  - Notebooks:
      - DEM Alkmaar: notebooks/dem_alkmaar.ipynb

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            docstring_style: numpy

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
